// In this file you can specify the trial data for your experiment


const trial_info = {
    key_press: _.shuffle([
        {
            question: "Are the objects same or different?",
            picture: "images/1_50_different.jpg",
            picture_number: 1,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/1_50_same.jpg",
            picture_number: 2,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/1_150_different.jpg",
            picture_number: 3,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/1_150_same.jpg",
            picture_number: 4,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/2_50_different.jpg",
            picture_number: 5,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/2_50_same.jpg",
            picture_number: 6,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/2_150_different.jpg",
            picture_number: 7,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/2_150_same.jpg",
            picture_number: 8,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/3_50_different.jpg",
            picture_number: 9,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/3_50_same.jpg",
            picture_number: 10,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/3_150_different.jpg",
            picture_number: 11,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/3_150_same.jpg",
            picture_number: 12,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/4_50_different.jpg",
            picture_number: 13,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/4_50_same.jpg",
            picture_number: 14,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/4_150_different.jpg",
            picture_number: 15,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/4_150_same.jpg",
            picture_number: 16,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/5_50_different.jpg",
            picture_number: 17,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/5_50_same.jpg",
            picture_number: 18,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/5_150_different.jpg",
            picture_number: 19,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/5_150_same.jpg",
            picture_number: 20,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/6_50_different.jpg",
            picture_number: 21,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/6_50_same.jpg",
            picture_number: 22,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/6_150_different.jpg",
            picture_number: 23,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/6_150_same.jpg",
            picture_number: 24,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/7_50_different.jpg",
            picture_number: 25,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/7_50_same.jpg",
            picture_number: 26,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/7_150_different.jpg",
            picture_number: 27,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/7_150_same.jpg",
            picture_number: 28,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/8_50_different.jpg",
            picture_number: 29,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/8_50_same.jpg",
            picture_number: 30,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/8_150_different.jpg",
            picture_number: 31,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/8_150_same.jpg",
            picture_number: 32,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/9_50_different.jpg",
            picture_number: 33,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/9_50_same.jpg",
            picture_number: 34,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/9_150_different.jpg",
            picture_number: 35,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/9_150_same.jpg",
            picture_number: 36,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/10_50_different.jpg",
            picture_number: 37,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/10_50_same.jpg",
            picture_number: 38,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/10_150_different.jpg",
            picture_number: 39,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/10_150_same.jpg",
            picture_number: 40,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/11_50_different.jpg",
            picture_number: 41,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/11_50_same.jpg",
            picture_number: 42,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/11_150_different.jpg",
            picture_number: 43,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/11_150_same.jpg",
            picture_number: 44,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/12_50_different.jpg",
            picture_number: 45,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/12_50_same.jpg",
            picture_number: 46,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/12_150_different.jpg",
            picture_number: 47,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/12_150_same.jpg",
            picture_number: 48,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/13_50_different.jpg",
            picture_number: 49,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/13_50_same.jpg",
            picture_number: 50,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/13_150_different.jpg",
            picture_number: 51,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/13_150_same.jpg",
            picture_number: 52,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/14_50_different.jpg",
            picture_number: 53,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/14_50_same.jpg",
            picture_number: 54,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/14_150_different.jpg",
            picture_number: 55,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/14_150_same.jpg",
            picture_number: 56,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/15_50_different.jpg",
            picture_number: 57,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/15_50_same.jpg",
            picture_number: 58,
            degree: 50,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/15_150_different.jpg",
            picture_number: 59,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'different',
            correct: 'different'
        },
        {
            question: "Are the objects same or different?",
            picture: "images/15_150_same.jpg",
            picture_number: 60,
            degree: 150,
            key1: 'b',
            key2: 'n',
            b: 'same',
            n: 'different',
            expected: 'same',
            correct: 'same'
        },
    ]),
};
